---
version: 0.1.2
slug: ha_boringproxy
name: BoringProxy-client for Home Assistant
url: https://github.com/hannpet/ha_boringproxy
description: Simple client that connects to a BoringProxy-server. A way to give HomeAssistant a public IP without too much hassle.
codenotary: notary@home-assistant.io
advanced: true
arch:
  - aarch64
host_network: true
options:
  server: myserver.io
  user: admin
  token: 12345678abcdefgh
  clientid: myhassio
  timeout: 6h
schema:
  server: str
  user: str
  token: str
  clientid: str
  timeout: list(3h|4h|5h|6h|24h|72h)?
startup: application
init: false
